version: '3.9'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:80"        # на хосте порт 8000 будет перенаправлен в контейнер (порт 80, который указан в Dockerfile)
    secrets:
      - db_host
      - db_port
      - db_name
      - db_user
      - db_pass
      - secret_auth    
    depends_on:
      - postgres
      - pgadmin
    networks:
      - app-network
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - 5051:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - app-network

secrets:
  db_host:
    file: ./secrets/db_host
  db_port:
    file: ./secrets/db_port
  db_name:
    file: ./secrets/db_name
  db_user:
    file: ./secrets/db_user
  db_pass:
    file: ./secrets/db_pass
  secret_auth:
    file: ./secrets/secret_auth

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
