version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_container
    ports:
      - 5434:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./csv:/csv
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - pg_network

networks:
  pg_network:
    driver: bridge

volumes:
  postgres_data:

